theory Config
  imports Main Types
begin

definition GENESIS_EPOCH :: Epoch where
  "GENESIS_EPOCH = Epoch (u64 0)"

definition TIMELY_SOURCE_FLAG_INDEX :: nat where
  "TIMELY_SOURCE_FLAG_INDEX = 0"

definition TIMELY_TARGET_FLAG_INDEX :: nat where
  "TIMELY_TARGET_FLAG_INDEX = 1"

definition TIMELY_HEAD_FLAG_INDEX :: nat where
  "TIMELY_HEAD_FLAG_INDEX = 2"

record Config =
  SLOTS_PER_HISTORICAL_ROOT :: u64
  HISTORICAL_ROOTS_LIMIT :: u64
  EPOCHS_PER_ETH1_VOTING_PERIOD :: u64
  SLOTS_PER_EPOCH :: u64
  VALIDATOR_REGISTRY_LIMIT :: u64
  EPOCHS_PER_HISTORICAL_VECTOR :: u64
  EPOCHS_PER_SLASHINGS_VECTOR :: u64
  JUSTIFICATION_BITS_LENGTH :: u64
  SYNC_COMMITTEE_SIZE :: u64

definition SLOTS_PER_ETH1_VOTING_PERIOD :: "Config \<Rightarrow> u64" where
  "SLOTS_PER_ETH1_VOTING_PERIOD c \<equiv> the (EPOCHS_PER_ETH1_VOTING_PERIOD c .* SLOTS_PER_EPOCH c)"

end