theory Config
  imports Main Types
begin

record Config =
  SLOTS_PER_HISTORICAL_ROOT :: u64
  HISTORICAL_ROOTS_LIMIT :: u64
  EPOCHS_PER_ETH1_VOTING_PERIOD :: u64
  SLOTS_PER_EPOCH :: u64
  VALIDATOR_REGISTRY_LIMIT :: u64
  EPOCHS_PER_HISTORICAL_VECTOR :: u64
  EPOCHS_PER_SLASHINGS_VECTOR :: u64
  JUSTIFICATION_BITS_LENGTH :: u64
  SYNC_COMMITTEE_SIZE :: u64

definition SLOTS_PER_ETH1_VOTING_PERIOD :: "Config \<Rightarrow> u64" where
  "SLOTS_PER_ETH1_VOTING_PERIOD c \<equiv> the (EPOCHS_PER_ETH1_VOTING_PERIOD c .* SLOTS_PER_EPOCH c)"

end